import jsPDF from "jspdf";
import { DealInput, ScoringResult } from "../../core/types";
import { addPage1 } from "./templates/page1";
import { addPage2 } from "./templates/page2";
import { addPage3 } from "./templates/page3";
import { addPage4 } from "./templates/page4";
import { addPage5 } from "./templates/page5";
import { addPage6 } from "./templates/page6";

export interface DealReportData {
  deal: DealInput;
  result: ScoringResult;
  analysisDate: Date;
  analystName: string;
  notes?: string;
  followUpActions?: string[];
  propertyCondition?: "Good" | "Fair" | "Poor";
  tenantQuality?: "A" | "B" | "C";
}

export class DealPDFGenerator {
  private pdf: jsPDF;
  private data: DealReportData;
  private pageHeight: number = 297; // A4 in mm
  private pageWidth: number = 210;
  private margin: number = 15;
  private currentY: number = 20;

  constructor(data: DealReportData) {
    this.pdf = new jsPDF("p", "mm", "a4");
    this.data = data;
  }

  generate(): jsPDF {
    // Add each page in order
    this.addHeaderFooter();
    this.currentY = 20; // Reset for page 1

    addPage1(this.pdf, this.data, this.currentY);
    this.pdf.addPage();
    this.currentY = 20;

    addPage2(this.pdf, this.data, this.currentY);
    this.pdf.addPage();
    this.currentY = 20;

    addPage3(this.pdf, this.data, this.currentY);
    this.pdf.addPage();
    this.currentY = 20;

    addPage4(this.pdf, this.data, this.currentY);
    this.pdf.addPage();
    this.currentY = 20;

    addPage5(this.pdf, this.data, this.currentY);
    this.pdf.addPage();
    this.currentY = 20;

    addPage6(this.pdf, this.data, this.currentY);

    return this.pdf;
  }

  save(): void {
    const filename = this.generateFilename();
    this.pdf.save(filename);
  }

  private addHeaderFooter(): void {
    // Add header and footer to each page
    this.pdf.setFontSize(8);
    this.pdf.setTextColor(100, 100, 100);

    // Footer on all pages
    this.pdf.setFont("helvetica", "italic");
    this.pdf.text(
      "Generated by Cash-Only Property Analyzer PWA • Doctrine-Driven Capital Allocation",
      this.pageWidth / 2,
      this.pageHeight - 10,
      { align: "center" }
    );
  }

  private generateFilename(): string {
    const dateStr = this.data.analysisDate.toISOString().slice(0, 10);
    const status = this.data.result.status;
    const score = this.data.result.finalScore;
    const name = this.data.deal.name.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 30);

    return `${dateStr}_${name}_${status}_${score}.pdf`;
  }
}

// Convenience function
export function generateDealReportPDF(data: DealReportData): void {
  const generator = new DealPDFGenerator(data);
  const pdf = generator.generate();
  generator.save();
}
